version: '3.7'

services:
  database_agendamento:
    image: postgres
    container_name: database_agendamento
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=agendamento
      - POSTGRES_DB=agendamento
    volumes:
      - pgdata:/data/postgres
  app:
    build: .
    container_name: agendamento-app
    ports: 
      - 3333:3333
    volumes:
      - .:/usr/app
      - /usr/app/node_modules

    links:
      - database_agendamento
    depends_on:
      - database_agendamento

volumes:
  pgdata:
    driver: local