version: '3.7'

services:
  database_agendamento:
    image: postgres
    container_name: database_agendamento
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=agendamento
      - POSTGRES_DB=agendamento
    volumes:
      - pgdata:/data/postgres

volumes:
  pgdata:
    driver: local